// test file for our lexer
// output.txt is the output file generated by the lexer after the make command is executed

/*
    Made by Barun Parua and Navaneeth Shaji
    Roll Numbers: 21CS10014 and 21CS30032
    Assignment 3 - Lexer for tinyC
*/

// struct point
// {
//     int x_coord;
//     int y_coord;
// } *p1;

int max(int x, int y)
{
    if (x > y)
    {
        return x;
    }
    else
    {
        return y;
    }
}

void swap(int* x, int* y)
{
    int temp = *x;
    *x = *y;
    *y = temp;

    return;
}

int main()
{
    auto alpha1 = 10;
    float _beta = 40.0;
    int c = alpha1 * _beta;
    alpha1 = alpha1 >> 1;
    c += 1;
    alpha1++;
    int x = alpha1&c;
    x = alpha1|c;
    x = alpha1^c;

    long long int deca10 = 1e7;
    deca10 /= 10000000;
    short int e = 1;
    double f = 1.0;
    long double g;
    g = 1.0e-10;

    char zebra = 'z';
    char* str = "Hello World";
    enum days {MON, TUE, WED, THU, FRI, SAT, SUN};
    enum days day = MON;

    do {
        alpha1++;
    } while (alpha1 < 10);

    while (alpha1 < 10)
    {
        alpha1++;
    }

    for (int iter = 0; iter < 10; iter++)
    {
        continue;
    }

    if (alpha1 == 10)
    {
        alpha1 = _beta;
    }
    else
    {
        alpha1 = c;
    }

    // p1->x_coord = 10;
    // p1->y_coord = 20;

    int x,y;

    x = 10;
    y = 20;

    x=x&&y;
    x=x||y;
    x=!y;
    x=x<y;
    x=x>y;
    x=x<=y;
    x=x>=y;
    x=x==y;
    x=x!=y;
    x=x<<y;
    x=x>>y;


    

    return 0;
}